---
title: "COVID-19 Project Graphs"
date: 2020-10-14
output:
  github_document:
    toc: true
---

```{r setup, message = FALSE}
library(tidyverse)
library(ggrepel)
library(gridExtra)
```

```{r download_data, warning = FALSE}
df_pop <- read.csv(file = "data/ACSDT5Y2018.B01003_2021-10-05T112429/ACSDT5Y2018.B01003_data_with_overlays_2021-10-05T112340.csv", skip = 1)
df_dummy <- read.csv("./data/ACSDT5Y2018.B19013_data_with_overlays_2021-10-18T125201.csv", skip = 1)
url_counties <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
url_vaccines <- "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv"

filename_nyt <- "./data/nyt_counties.csv"
filename_cdc <- "./data/cdc_vaccines.csv"

## Download the data locally
curl::curl_download(
        url_counties,
        destfile = filename_nyt
      )
curl::curl_download(
        url_vaccines,
        destfile = filename_cdc
      )


## Loads the downloaded csv
df_covid <- read_csv(filename_nyt)
df_vaccines <- read_csv(filename_cdc)

df_dummy %>% summary()

```
```{r clean up income}
df_income <-
  df_dummy %>%
  separate(
    col = 'Geographic.Area.Name',
    into = c('county', 'state'),
    sep = ','
  ) %>%
  separate(
    col = id,
    into = c("id","fips"),
    sep = -5
  ) %>%
  select(
    fips, 
    state, 
    county, 
    median_income = 5
  )

df_income$median_income = as.numeric(df_income$median_income)

df_income
```

```{r cleaning_data}
df_pop_fips <- df_pop %>% 
  filter(nchar(id) > 9) %>% 
  separate(col = id, into = c(NA, "fips"), sep = -5, remove = FALSE)

df_data <- 
  inner_join(
    df_covid,
    df_pop_fips,
    by = "fips"
  ) %>% 
  inner_join(
    df_income,
    by = "fips"
  ) %>%
  select(
    date,
    county = county.x,
    state = county.x,
    fips,
    cases,
    deaths,
    population = `Estimate..Total`,
    median_income
  )

df_normalized <-
  df_data %>% 
  mutate(
    cases_per100k = 100000 * cases / population, 
    deaths_per100k = 100000 * deaths / population
  )

df_fatality <- 
  df_normalized %>%
  group_by(county) %>% 
  filter(date == max(date)) %>% 
  summarize(state, fatality = 100 * deaths_per100k / cases_per100k, median_income, population, cases_per100k, deaths_per100k)

```

```{r data manipulation}
df_graph <- 
  df_fatality %>% 
  filter(population > 1e3 & population < 1e7 & median_income > 25000) %>% 
  mutate(
    pop_bin = cut(x = population, breaks = c(0, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8))
  )

cor_fatality <-
  df_graph %>%
  group_by(pop_bin) %>%
  summarize(
    rho = cor(median_income, fatality, method = "spearman", use = "pairwise.complete.obs"),
    std = sd(fatality, na.rm = TRUE)
  )

cor_fatality

cor_deaths <-
  df_graph %>%
  group_by(pop_bin) %>%
  summarize(
    rho = cor(median_income, deaths_per100k, method = "spearman", use = "pairwise.complete.obs"),
    std = sd(deaths_per100k, na.rm = TRUE)
  )

cor_deaths

cor_cases <-
  df_graph %>%
  group_by(pop_bin) %>%
  summarize(
    rho = cor(median_income, cases_per100k, method = "spearman", use = "pairwise.complete.obs"),
    std = sd(cases_per100k, na.rm = TRUE)
  )

cor_cases
```

```{r graphing}
g_fatality <- df_graph %>% 
  ggplot(aes(median_income, fatality, color = pop_bin)) +
  geom_point(na.rm = TRUE, size = 0.8) +
  geom_smooth(method = "glm", formula = "y ~ log(x)", na.rm = TRUE, se = TRUE) +
  theme(legend.position = "bottom") +
  scale_x_log10(labels = scales::label_number_si()) +
  labs(
    x = "Median Income",
    y = "Fatality Rate (%)",
    color = "Population:",
    title = "County Fatality Rates vs Income"
  ) +
  scale_color_discrete(labels = c("1K-10K", "10K-100K", "100K-1M", "1M-10M")) +
  facet_grid(pop_bin ~ .) +
  theme(strip.text.y = element_blank()) +
  geom_text(
    data = cor_fatality, 
    aes(label = paste("corr = ", round(rho, 2), sep = " ")), 
    x = Inf, 
    y = Inf,
    vjust = 1.5, 
    hjust = 1.2, 
    show.legend = FALSE
  ) +
  geom_text(
    data = cor_fatality, 
    aes(label = paste("std = ", round(std, 2), sep = " ")), 
    x = Inf, 
    y = Inf,
    vjust = 3, 
    hjust = 1.2, 
    show.legend = FALSE
  )


g_deaths <- df_graph %>% 
  ggplot(aes(median_income, deaths_per100k, color = pop_bin)) +
  geom_point(na.rm = TRUE, size = 0.8) +
  geom_smooth(method = "glm", formula = "y ~ log(x)", na.rm = TRUE, se = TRUE) +
  theme(legend.position = "bottom") +
  scale_x_log10(labels = scales::label_number_si()) +
  labs(
    x = "Median Income",
    y = "Deaths per 100K",
    color = "Population:",
    title = "County Death Rates vs Income"
  ) +
  scale_color_discrete(labels = c("1K-10K", "10K-100K", "100K-1M", "1M-10M")) +
  facet_grid(pop_bin ~ .) +
  theme(strip.text.y = element_blank()) +
  geom_text(
    data = cor_deaths, 
    aes(label = paste("corr = ", round(rho, 2), sep = " ")), 
    x = Inf, 
    y = Inf,
    vjust = 1.5, 
    hjust = 1.2, 
    show.legend = FALSE
  ) +
  geom_text(
    data = cor_deaths, 
    aes(label = paste("std = ", round(std, 2), sep = " ")), 
    x = Inf, 
    y = Inf,
    vjust = 3, 
    hjust = 1.2, 
    show.legend = FALSE
  )


g_cases <- df_graph %>% 
  ggplot(aes(median_income, cases_per100k, color = pop_bin)) +
  geom_point(na.rm = TRUE, size = 0.8) +
  geom_smooth(method = "glm", formula = "y ~ log(x)", na.rm = TRUE, se = TRUE) +
  theme(legend.position = "bottom") +
  scale_x_log10(labels = scales::label_number_si()) +
  labs(
    x = "Median Income",
    y = "Cases per 100K",
    color = "Population:",
    title = "County Case Rates vs Income"
  ) +
  scale_color_discrete(labels = c("1K-10K", "10K-100K", "100K-1M", "1M-10M")) +
  facet_grid(pop_bin ~ .) +
  theme(strip.text.y = element_blank()) +
  geom_text(
    data = cor_cases, 
    aes(label = paste("corr = ", round(rho, 2), sep = " ")), 
    x = Inf, 
    y = Inf,
    vjust = 1.5, 
    hjust = 1.2, 
    show.legend = FALSE
  ) +
  geom_text(
    data = cor_cases, 
    aes(label = paste("std = ", round(std, 2), sep = " ")), 
    x = Inf, 
    y = Inf,
    vjust = 3, 
    hjust = 1.2, 
    show.legend = FALSE
  )
```

```{r create plots, fig.width = 10, fig.height = 8}

grid.arrange(g_fatality, g_deaths, g_cases, nrow = 1)

g_fatality

ggsave(
  filename = "HeadlineGraph.png",
  plot = grid.arrange(g_fatality, g_deaths, g_cases, nrow = 1)
)
```









